### ISSUE TITLE
Creating a mutli-year event ends it at the new year (issue with frontmatter?)

### ISSUE THREAD

**Issue by simonfruehauf** [valentine195/obsidian-fantasy-calendar#22]
I created an event on a custom calendar through frontmatter 

```
fc-calendar: Calendar of Iska
fc-date:
  year: 1304
  month: Cervan
  day: 1
fc-end:
  year: 1337
  month: Pale
  day: 3
fc-category: War
```

This event however terminated at 1304, 32nd (last day of the month) of Fentar (last month of the year), and also didn't show up anywhere. 

When editing the event (through the context menu) i still saw the correct data (from the frontmatter).
